{% set name = "astroplan" %}
{% set version = "0.6" %}
{% set hash_type = "sha256" %}
{% set hash_value = "dd76407d372dceb3a1668353f2d8806e203e83e6930924c92decee1a9744a757" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --offline --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - astropy >=1.3
  run:
    - python
    - numpy >=1.6
    - astropy >=1.3
    - pytz
    - matplotlib

test:
  imports:
    - astroplan
    - astroplan.plots

about:
  home: https://github.com/astropy/astroplan
  license: BSD 3-clause
  license_file: 
    - LICENSE.rst 
    - licenses 

  license_family: BSD
  summary: Observation planning package for astronomers
  description: |
    astroplan is an observation planning package for astronomers that can help
    you plan for everything but the clouds. It is an in-development Astropy
    affiliated package that seeks to make your life as an observational
    astronomer a little less infuriating.
  doc_url: https://astroplan.readthedocs.io/
  dev_url: https://github.com/astropy/astroplan

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - bmorris3
