appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Q5EgvKWMgJGSPPt1BGglFmhcMagNmC54BATRHseBph8drIz/4fgKzA2UscSz/7mEnGQlzFnBxqbSb2PbPGOjYcDKmwk+mfOVjSMifwBkGojJI7/UrJW5D5VZdlWCdYpB5aWL16wXfmtRUfsQQ5edXXJHnPMNpD71hEDZ6qOGpk0PssgWheH+X74k8JFLMCPp11Co8WdkqpKiqu4AlIhBEoGKtn8WCTnyPJq73NdaXsC/oHuwMLpzaMr9oBY3H33ftvhKYbneGaX7wPZmDXzN9xxtRG2OiXX/ayxCAjO5bzG4eJ+wwQRi48MmIRFTSiJrY5zEGa2sM7eyg7IHDr1pCQ1Gdb/RHrS9i8TrHZGjNBCEpoOYNA0weD5lKQtF4UiHWFcjimB/AUxl5JHdpFVlRgo83qSB6tezq3Qm+yuI6jIC/eEoIazRhp9GOY9FnBX/8S5Iuhb+sltD0oyL2K9JiRzA9esEt/672ro9hxOHpb9bMZnsC8Ah8S0eLKLxebTsuDgDkSHq/cKMsUsAHa3PRSiMQo5M+AlUjnqreejkSEi99HwUBCJQg5ZeLQYJZU0v/uV2ALTyQGGYT1q7MiwmgwyZ9Q1uaqtuX5DV3vHGUu1jZnRgV8PsPaI1D3Ew9zy1URSwviJc6hsnFqamckjBNyww/OYKA0t/4InMhiDZ6PU=}
provider:
  win: azure
conda_forge_output_validation: true
