travis:
  secure:
    BINSTAR_TOKEN: nrtpZ7l3BLH4E6huGgRdk/DWuDiAsZ/fbMUgFfSiqf6zBTt2iwu8fxLZ4Uci/FB7SDRM4eqZlEa9kWeVEt13ge4Sei6PiK0IlbhoXbpDWEioB0ad/GR0tp5Cp2M7Ilv6VzuyIoNH3pwcyIA2OAd5J8GeXMq6uU+XTkLIPpGKjIP0OEKyC1dVPolE1CzvbbfqR0ZP/kbh6ZrLD0Ie5igbWI5qeTZbqH6ghvZg64tXr2BCk0zeqIugejCjB7UkMqtv4RbOanGBHyu5P9KyYxBjfNZedOFROjmC7WQn3cGsVNtGmDpU9ozNPDfm7gACoyiMcl05K6KU7Gcgne367T2yodekNADj7/cxogDSbaYbSAv6PV7LSIWTq8C2YPjLYps/y+XyV72BXuorcgQSW2FqNUCrZwUA93dZOSdrYavvVI1NUw9wwMFRZpt8IVNKSN81/zQpW8DxStO+PSD7GzB0HsvHNBDh6CRSHWACxN3WfM8GIiVs64hNVO9l43kCaOFvvEf55UEvjXpI4j/7G1FNPBLTe85xWKhsDbH/YzQcQ7zvBkfYAvgzGyZh4uP9y+WFUdiwbo882laJwmA8SIJODQ0yjVlFOL3YhAUdJrak5obrsIKlDv1NuGAzCK1Y+keIHYXp3zg1f5bVH3Q98QeEvR+33huuqnqvfMjNcX7RRDs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
