travis:
  secure:
    BINSTAR_TOKEN: NqngZFENzuTKTzH682j1UeojFK88iPyyb4TrNzYs1RGAwxoRXuFkfmF2B4JWwfBaO1Xl+LsctaorM2sUFS+oQgzzSMI8ThGf3s8hXdByHTqn7TgT/aKpUQEZTZ2u9j/Lea5opNpNRXPprwOVpRRb71nPe1XMkRUiZFvHYxWfX1KX4i+++XKAodKO1Rne4tvaiFQ+F2lCiY07SAKlQnU8Ukw1DBAciJnYbKG1JF5saYHiEkHEGY+V7QFdl2Rxim8mOX/DPwoeGqV/Wn/hWgPtVh9UZA6oPRpb7lNL1HlQHnpInzRY4PIREyKDhRnmd842bsiCHRSMy+ls4CqOJJ2bB0dM9ebacOPwk6IVBZQqlTTK3WUhAZBmV5bWs4P+gpW99Xg+Zvf22WiMaXoRqSfJEVqVpmPNEArx6W/81xpQULTOOxw1HqxrX41whu/P9dzBg7MH62Zc9F5/xjim+wjjaXeGjTfX1hl5Y5oOoGOigXp4j47DlCXdNLuDK2Ls8A3dtlR+FMAXCIWPPqsHIIZHOosqUmizDBttYzjKVJL2JUBhFw/L/zhjtOnFSu1MSe8wHMaoL7lKyayU0bXj1O9Uw82c/7s/5ALJ4pYi6sG/3byeyM+e2UVzf6AUWgOProFKp49xfDevzQ2h3Y33lo7kip2acTk/qTI2eGnvM5WCc2k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
